node_id: "validator2"
consensus:
  wave_timeout: 10s
  round_duration: 5s
  validator_set:
    - "validator1"
    - "validator2"
  quorum_size: 2
  listen_addr: "localhost:3001"
  seeds:
    - "localhost:3000"
  total_validators: 2

state:
  genesis_file: "genesis.json"

evm:
  chain_id: 1
  gas_limit: 8000000