node_id: "validator1"
consensus:
  wave_timeout: 10s
  round_duration: 5s
  validator_set:
    - "validator1"
    - "validator2"
  quorum_size: 2
  listen_addr: "0.0.0.0:3000"
  seeds:
    - "52.53.192.236:3000"
  total_validators: 2

state:
  genesis_file: "genesis.json"

evm:
  chain_id: 1
  gas_limit: 8000000 