node_id: "validator1"
consensus:
  wave_timeout: 10s
  round_duration: 1s
  validator_set:
    - "validator1"
    - "validator2"
    - "validator3"
  quorum_size: 2
  listen_addr: "localhost:8081"
  seeds:
    - "localhost:8082"
    - "localhost:8083"
  total_validators: 3

state:
  genesis_file: "genesis.json"

evm:
  chain_id: 1
  gas_limit: 8000000
  